name: Python test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install requirements
        run: |
          pip install --upgrade pip
          # avoid installing cuda support cause it is not used
          pip install torch==2.8.* --index-url https://download.pytorch.org/whl/cpu
          pip install -e .
      - name: Download test data
        run: |
          mkdir data
          curl -o data/showers.h5 https://syncandshare.desy.de/public.php/dav/files/tCMX2mFexPpmZC4
      - name: OT matching
        run: python allshowers/OT_match.py conf/transformer.yaml
      - name: Test with Unittest
        run: python -m unittest discover --verbose  -s test -p '*_test.py'
      - name: Fast development run
        run: python allshowers/train.py -d cpu --fast-dev-run conf/transformer.yaml
      - name: Generate new data
        run: |
          showerdata add-observables --overwrite data/showers.h5  # to ensure num_points_per_layer is present
          python allshowers/generator.py --batch-size=1 --device=cpu -n 2 --num-timesteps 3 results/test data/showers.h5
